/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import controlador.ControladorPrincipal;

/**
 *
 * @author selected
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregarAnimal = new javax.swing.JButton();
        btnCalcularComida = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblKgCarnivoros = new javax.swing.JLabel();
        lblKgHerbivoros = new javax.swing.JLabel();
        lblKgTotal = new javax.swing.JLabel();
        sector1 = new javax.swing.JPanel();
        lblIdSector1 = new javax.swing.JLabel();
        lblEspeciesSector1 = new javax.swing.JLabel();
        lblCantidadSector1 = new javax.swing.JLabel();
        lblCoordSector1 = new javax.swing.JLabel();
        lblEmpleado1 = new javax.swing.JLabel();
        sector2 = new javax.swing.JPanel();
        lblIdSector2 = new javax.swing.JLabel();
        lblEspeciesSector2 = new javax.swing.JLabel();
        lblCoordSector2 = new javax.swing.JLabel();
        lblCantidadSector2 = new javax.swing.JLabel();
        lblEmpleado2 = new javax.swing.JLabel();
        sector3 = new javax.swing.JPanel();
        lblIdSector3 = new javax.swing.JLabel();
        lblEspeciesSector3 = new javax.swing.JLabel();
        lblCantidadSector3 = new javax.swing.JLabel();
        lblCoordSector3 = new javax.swing.JLabel();
        lblEmpleado3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btnAgregarAnimal.setText("Agregar Animal");
        btnAgregarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAnimalActionPerformed(evt);
            }
        });

        btnCalcularComida.setText("Calcular Comida");
        btnCalcularComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularComidaActionPerformed(evt);
            }
        });

        jLabel1.setText("Kgs Carnívoros");

        jLabel2.setText("Kgs Herbívoros");

        jLabel3.setText("Kgs Total");

        lblKgCarnivoros.setText("0");

        lblKgHerbivoros.setText("0");

        lblKgTotal.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKgHerbivoros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(lblKgTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKgCarnivoros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblKgCarnivoros))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblKgHerbivoros, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblKgTotal))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcularComida, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnAgregarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarAnimal)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcularComida)
                        .addGap(32, 32, 32))))
        );

        sector1.setBackground(new java.awt.Color(153, 153, 153));
        sector1.setPreferredSize(new java.awt.Dimension(167, 0));

        lblIdSector1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdSector1.setText("1");

        lblEspeciesSector1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCantidadSector1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCoordSector1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoordSector1.setText("1");

        lblEmpleado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpleado1.setText("1");

        javax.swing.GroupLayout sector1Layout = new javax.swing.GroupLayout(sector1);
        sector1.setLayout(sector1Layout);
        sector1Layout.setHorizontalGroup(
            sector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sector1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdSector1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEspeciesSector1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCantidadSector1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCoordSector1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sector1Layout.setVerticalGroup(
            sector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sector1Layout.createSequentialGroup()
                .addComponent(lblIdSector1)
                .addGap(18, 18, 18)
                .addComponent(lblEspeciesSector1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadSector1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(lblCoordSector1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmpleado1)
                .addGap(4, 4, 4))
        );

        sector2.setBackground(new java.awt.Color(153, 153, 153));
        sector2.setForeground(new java.awt.Color(204, 204, 204));
        sector2.setPreferredSize(new java.awt.Dimension(167, 120));

        lblIdSector2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdSector2.setText("2");

        lblEspeciesSector2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCoordSector2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoordSector2.setText("1");

        lblCantidadSector2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblEmpleado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpleado2.setText("1");

        javax.swing.GroupLayout sector2Layout = new javax.swing.GroupLayout(sector2);
        sector2.setLayout(sector2Layout);
        sector2Layout.setHorizontalGroup(
            sector2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sector2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sector2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdSector2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEspeciesSector2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCoordSector2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCantidadSector2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpleado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sector2Layout.setVerticalGroup(
            sector2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sector2Layout.createSequentialGroup()
                .addComponent(lblIdSector2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblEspeciesSector2)
                .addGap(18, 18, 18)
                .addComponent(lblCantidadSector2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCoordSector2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmpleado2)
                .addGap(6, 6, 6))
        );

        sector3.setBackground(new java.awt.Color(153, 153, 153));
        sector3.setForeground(new java.awt.Color(153, 153, 153));

        lblIdSector3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdSector3.setText("3");

        lblEspeciesSector3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspeciesSector3.setText("33");

        lblCantidadSector3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCoordSector3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoordSector3.setText("1");

        lblEmpleado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpleado3.setText("1");

        javax.swing.GroupLayout sector3Layout = new javax.swing.GroupLayout(sector3);
        sector3.setLayout(sector3Layout);
        sector3Layout.setHorizontalGroup(
            sector3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sector3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sector3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdSector3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCoordSector3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEspeciesSector3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(lblCantidadSector3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpleado3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sector3Layout.setVerticalGroup(
            sector3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sector3Layout.createSequentialGroup()
                .addComponent(lblIdSector3)
                .addGap(29, 29, 29)
                .addComponent(lblEspeciesSector3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblCantidadSector3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCoordSector3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmpleado3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sector3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sector2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(sector1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sector1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sector2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sector3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnimalActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.mostrarVistaAgregarAnimal();
    }//GEN-LAST:event_btnAgregarAnimalActionPerformed

    private void btnCalcularComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularComidaActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.botonCalcularComida();
    }//GEN-LAST:event_btnCalcularComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    public JLabel getLblCantidadSector1() {
        return lblCantidadSector1;
    }

    public JLabel getLblCantidadSector2() {
        return lblCantidadSector2;
    }

    public JLabel getLblCantidadSector3() {
        return lblCantidadSector3;
    }

    public JLabel getLblCoordSector1() {
        return lblCoordSector1;
    }

    public JLabel getLblCoordSector2() {
        return lblCoordSector2;
    }

    public JLabel getLblCoordSector3() {
        return lblCoordSector3;
    }

    public JLabel getLblEmpleado1() {
        return lblEmpleado1;
    }

    public JLabel getLblEmpleado2() {
        return lblEmpleado2;
    }

    public JLabel getLblEmpleado3() {
        return lblEmpleado3;
    }

    public JLabel getLblEspeciesSector1() {
        return lblEspeciesSector1;
    }

    public JLabel getLblEspeciesSector2() {
        return lblEspeciesSector2;
    }

    public JLabel getLblEspeciesSector3() {
        return lblEspeciesSector3;
    }

    public JLabel getLblIdSector1() {
        return lblIdSector1;
    }

    public JLabel getLblIdSector2() {
        return lblIdSector2;
    }

    public JLabel getLblIdSector3() {
        return lblIdSector3;
    }

    public JLabel getLblKgCarnivoros() {
        return lblKgCarnivoros;
    }

    public JLabel getLblKgHerbivoros() {
        return lblKgHerbivoros;
    }

    public JLabel getLblKgTotal() {
        return lblKgTotal;
    }

    public JPanel getSector1() {
        return sector1;
    }

    public JPanel getSector2() {
        return sector2;
    }

    public JPanel getSector3() {
        return sector3;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAnimal;
    private javax.swing.JButton btnCalcularComida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCantidadSector1;
    private javax.swing.JLabel lblCantidadSector2;
    private javax.swing.JLabel lblCantidadSector3;
    private javax.swing.JLabel lblCoordSector1;
    private javax.swing.JLabel lblCoordSector2;
    private javax.swing.JLabel lblCoordSector3;
    private javax.swing.JLabel lblEmpleado1;
    private javax.swing.JLabel lblEmpleado2;
    private javax.swing.JLabel lblEmpleado3;
    private javax.swing.JLabel lblEspeciesSector1;
    private javax.swing.JLabel lblEspeciesSector2;
    private javax.swing.JLabel lblEspeciesSector3;
    private javax.swing.JLabel lblIdSector1;
    private javax.swing.JLabel lblIdSector2;
    private javax.swing.JLabel lblIdSector3;
    private javax.swing.JLabel lblKgCarnivoros;
    private javax.swing.JLabel lblKgHerbivoros;
    private javax.swing.JLabel lblKgTotal;
    private javax.swing.JPanel sector1;
    private javax.swing.JPanel sector2;
    private javax.swing.JPanel sector3;
    // End of variables declaration//GEN-END:variables
}
